server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pnc_hotel_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

app:
  jwt:
    secret: JAi2uehrLzUQDS9Zmuxx3NucGD3JHzGjpwO67/sugPQ=

logging:
  level:
    com.uca.pncparcialfinalhotel: DEBUG